apiVersion: v2
name: poste-io
version: 0.4.0
description: A Help Chart for the poste-io mail server.

appVersion: 2.5.7
home: https://poste.io/
icon: https://poste.io/favicon.ico
keywords: [mail, "poste.io", POP3, SMTP, IMAP, Spamassassin, WebMail, WebAdmin]

maintainers:
  - email: bpteodor@users.noreply.github.com
    name: Teo

sources:
  - https://github.com/bran-tech/poste-io

kubeVersion: ">=1.28.0-0"

dependencies:
  # https://github.com/bjw-s-labs/helm-charts/tree/main/charts/library/common
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts/