{{- $fullName := include "poste-io.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "poste-io.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  #strategy:
  #  type: {{ .Values.deploy.strategy }}
  selector:
    matchLabels:
      {{- include "poste-io.selectorLabels" . | nindent 6 }}
  serviceName: {{ $fullName }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "poste-io.selectorLabels" . | nindent 8 }}
    spec:
      {{- toYaml .Values.deploy.network | nindent 6 }}
      # init containers
      {{- if .Values.initContainers }}
      initContainers: 
      {{- toYaml .Values.initContainers | nindent 6 }}
      {{- end }}
      # main container
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          hostIP: 127.0.0.1
        - name: sieve
          containerPort: 4190
          hostIP: 127.0.0.1
        - containerPort: 25
        - containerPort: 465
        - containerPort: 587
        - containerPort: 110
        - containerPort: 143
        - containerPort: 993
        - containerPort: 995
        env:
          {{- toYaml .Values.env | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 25
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
        volumeMounts:
          {{- range $name, $i := .Values.deploy.persistence }}
          {{- if $i.mnt }}
          - name: {{ $name }}
            {{- toYaml $i.mnt | nindent 12 }}
          {{- end }}
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
        {{- range $name,$i := .Values.deploy.persistence }}
        - name: {{ $name }}
          {{- if $i.vol }}
          {{- toYaml $i.vol | nindent 10 }}
          {{ else }}
          {{- toYaml $i.defaultVol | nindent 10 }}
          {{- end }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
